[package]
name = "vector-proj"
version = "0.1.0"
edition = "2021"

[lib]
name = "vector_lib"
path = "src/lib.rs"

[[bin]]
name = "vector_bin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl_ops = "0.1.1"
